version: '3.8'

services:
  ghcsd:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghcsd
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DEBUG=0
    volumes:
      - ghcsd_config:/root/.config/ghcsd
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  ghcsd_config:
    name: ghcsd_config